# Codigo de mi repositorio (https://github.com/JunalChowdhuryG/Actividades-CC3S2/blob/main/Actividad-14/Makefile)
# variables
PYTHON = python
PIP = pip
TEST_DIR = tests
COV_DIR = htmlcov
FLAKE_REPORT = flake8-report.txt

# instalar dependencias
deps:
	$(PIP) install -r requirements.txt

# ejecutar pruebas
test:
	$(PYTHON) -m pytest $(TEST_DIR) -v

# ejecutar pruebas con detención en el primer fallo
test-exitfirst:
	$(PYTHON) -m pytest $(TEST_DIR) -v --exitfirst


# ejecutar linting con flake8
lint:
	$(PYTHON) -m flake8 models tests > $(FLAKE_REPORT) || true

# limpiar archivos generados
clean:
	rm -rf .pytest_cache .coverage $(COV_DIR) __pycache__ */__pycache__ $(FLAKE_REPORT) htmlcov test.db

#construir imagen
build:
	docker-compose up -d --build

#desplegar
deploy:
	docker-compose up -d --build


# generar informe de cobertura
cov:
	$(PYTHON) -m pytest $(TEST_DIR) --cov=models --cov-report=term --cov-report=html


# ejecutar todas las tareas
all: deps  lint test build deploy

.PHONY: deps test test-exitfirst cov lint clean build deploy all



