
#referencia de mi repo de actividades (https://github.com/JunalChowdhuryG/Actividades-CC3S2/tree/main/.github/workflows)
name:  CI Examen Sustitorio

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    # clonar repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # configurar Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # ejecutar flake8
    - name: Run flake8
      run: |
        flake8 

    # ejecutar  pruebas de cobertura
    - name: Run tests with coverage
      run: |
       pytest tests/ --cov=models --cov-report=html

    # subir informe cobertura como artefacto
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: .

    #shellcheck
    - name: Run shellcheck
      run: |
        apt-get install shellcheck
        shellcheck scripts/ci.sh

    #generar changelog.md con los ultimos 5 commits
    - name: Generate changelog
      run: |
        git log -n 5 --pretty=format:"* %s" > changelog.md